from datetime import date

from sqlalchemy.orm import Session

from .models import IndicatorDefinition, SourceRegistry

SOURCES = [
    {
        "id": "world_bank",
        "provider": "World Bank",
        "dataset": "World Development Indicators",
        "official_url": "https://api.worldbank.org/v2/",
        "terms_url": "https://www.worldbank.org/ext/en/legal/terms-conditions",
        "license_status": "待商业复核",
        "attribution_text": "Source: World Bank World Development Indicators",
        "reviewed_at": date(2026, 8, 15),
    },
    {
        "id": "census_us",
        "provider": "U.S. Census Bureau",
        "dataset": "Advance Monthly Sales for Retail and Food Services",
        "official_url": "https://www.census.gov/retail/marts/www/timeseries.html",
        "terms_url": "https://www.census.gov/about/policies.html",
        "license_status": "待署名",
        "attribution_text": (
            "Source: U.S. Census Bureau, Advance Monthly Sales for Retail and Food Services"
        ),
        "reviewed_at": date(2026, 8, 15),
    },
    {
        "id": "treasury_us",
        "provider": "U.S. Department of the Treasury",
        "dataset": "Daily Treasury Par Yield Curve Rates",
        "official_url": "https://home.treasury.gov/resource-center/data-chart-center/interest-rates/",
        "terms_url": "https://home.treasury.gov/utility/policies-and-notices",
        "license_status": "待署名",
        "attribution_text": "Source: U.S. Department of the Treasury",
        "reviewed_at": date(2026, 8, 15),
    },
    {
        "id": "bls",
        "provider": "U.S. Bureau of Labor Statistics",
        "dataset": "BLS Public Data API",
        "official_url": "https://api.bls.gov/publicAPI/v2/timeseries/data/",
        "terms_url": "https://www.bls.gov/developers/termsOfService.htm",
        "license_status": "待署名",
        "attribution_text": (
            "Source: U.S. Bureau of Labor Statistics. BLS.gov cannot vouch for data or "
            "analyses after retrieval."
        ),
        "reviewed_at": date(2026, 8, 15),
    },
    {
        "id": "fred",
        "provider": "Federal Reserve Bank of St. Louis",
        "dataset": "FRED/ALFRED",
        "official_url": "https://api.stlouisfed.org/fred/",
        "terms_url": "https://fred.stlouisfed.org/docs/api/terms_of_use.html",
        "license_status": "逐系列复核",
        "attribution_text": (
            "This product uses the FRED® API but is not endorsed or certified by the "
            "Federal Reserve Bank of St. Louis."
        ),
        "reviewed_at": date(2026, 8, 15),
    },
    {
        "id": "boj",
        "provider": "Bank of Japan",
        "dataset": "BOJ Time-Series Data Search",
        "official_url": "https://www.stat-search.boj.or.jp/api/v1/",
        "terms_url": "https://www.stat-search.boj.or.jp/info/api_notice_en.pdf",
        "license_status": "待署名",
        "attribution_text": (
            "This service uses the API provided by the Bank of Japan Time-Series Data Search."
        ),
        "reviewed_at": date(2026, 8, 15),
    },
    {
        "id": "estat_jp",
        "provider": "Statistics Bureau of Japan",
        "dataset": "2020-Base Consumer Price Index, Goods and Service Group",
        "official_url": "https://www.e-stat.go.jp/en/stat-search/files?toukei=00200573&tstat=000001150147",
        "terms_url": "https://www.e-stat.go.jp/en/terms-of-use",
        "license_status": "待署名",
        "attribution_text": "Source: Statistics Bureau of Japan, 2020-Base Consumer Price Index",
        "reviewed_at": date(2026, 8, 16),
    },
    {
        "id": "nbs_cn",
        "provider": "National Bureau of Statistics of China",
        "dataset": "国家数据及官方发布文件",
        "official_url": "https://data.stats.gov.cn/",
        "terms_url": "https://www.stats.gov.cn/",
        "license_status": "待自动化与再展示复核",
        "attribution_text": "来源：中华人民共和国国家统计局",
        "reviewed_at": date(2026, 8, 15),
    },
    {
        "id": "pbc_cn",
        "provider": "People's Bank of China",
        "dataset": "城镇储户问卷调查报告",
        "official_url": "https://www.pbc.gov.cn/diaochatongjisi/116219/116227/index.html",
        "terms_url": "https://www.pbc.gov.cn/",
        "license_status": "待自动化与再展示复核",
        "attribution_text": "来源：中国人民银行调查统计司",
        "reviewed_at": date(2026, 8, 16),
    },
]

GEOGRAPHIES = {"CN": "CHN", "US": "USA", "JP": "JPN", "GLOBAL": "WLD"}
INDICATOR_TEMPLATES = [
    {
        "slug": "LABOR_AGE_POP",
        "name_zh": "劳动年龄人口",
        "name_en": "Population ages 15-64",
        "external_code": "SP.POP.1564.TO",
        "dimension": "DEMOGRAPHY",
        "frequency": "A",
        "unit": "people",
        "transformation": {"features": ["yoy", "five_year_cagr", "percentile"]},
        "quality_grade": "A",
    },
    {
        "slug": "RD_GDP",
        "name_zh": "研发支出占GDP比重",
        "name_en": "Research and development expenditure (% of GDP)",
        "external_code": "GB.XPD.RSDV.GD.ZS",
        "dimension": "TECH",
        "frequency": "A",
        "unit": "% GDP",
        "transformation": {"features": ["level", "five_year_change", "percentile"]},
        "quality_grade": "B",
    },
    {
        "slug": "GDP_GROWTH",
        "name_zh": "实际GDP增长率",
        "name_en": "GDP growth (annual %)",
        "external_code": "NY.GDP.MKTP.KD.ZG",
        "dimension": "REAL",
        "frequency": "A",
        "unit": "%",
        "transformation": {"features": ["level", "five_year_average", "percentile"]},
        "quality_grade": "A",
    },
    {
        "slug": "PRIVATE_CREDIT_GDP",
        "name_zh": "私营部门国内信贷占GDP比重",
        "name_en": "Domestic credit to private sector (% of GDP)",
        "external_code": "FS.AST.PRVT.GD.ZS",
        "dimension": "CREDIT",
        "frequency": "A",
        "unit": "% GDP",
        "transformation": {"features": ["level", "five_year_change", "percentile"]},
        "quality_grade": "A",
    },
]

MONTHLY_INDICATORS = [
    {
        "id": "ESTAT_JP_CPI_YOY",
        "source_id": "estat_jp",
        "external_code": "000032103935:all_items",
        "name_zh": "日本居民消费价格同比",
        "name_en": "Japan CPI, all items, year-on-year",
        "geography": "JP", "dimension": "INFLATION", "frequency": "M", "unit": "%",
        "transformation": {"features": ["level", "three_month_change", "percentile"]},
        "quality_grade": "A", "active": True,
    },
    {
        "id": "ESTAT_JP_GOODS_CPI_YOY",
        "source_id": "estat_jp",
        "external_code": "000032103935:goods",
        "name_zh": "日本商品价格同比",
        "name_en": "Japan CPI goods, year-on-year",
        "geography": "JP", "dimension": "INFLATION", "frequency": "M", "unit": "%",
        "transformation": {"features": ["level", "three_month_change", "percentile"]},
        "quality_grade": "A", "active": True,
    },
    {
        "id": "ESTAT_JP_SERVICES_CPI_YOY",
        "source_id": "estat_jp",
        "external_code": "000032103935:services",
        "name_zh": "日本服务价格同比",
        "name_en": "Japan CPI services, year-on-year",
        "geography": "JP", "dimension": "INFLATION", "frequency": "M", "unit": "%",
        "transformation": {"features": ["level", "three_month_change", "percentile"]},
        "quality_grade": "A", "active": True,
    },
    {
        "id": "PBC_CN_PRICE_EXPECTATION",
        "source_id": "pbc_cn",
        "external_code": "URBAN_DEPOSITOR:PRICE_EXPECTATION_INDEX",
        "name_zh": "中国居民未来物价预期指数",
        "name_en": "China urban depositor price expectation index",
        "geography": "CN",
        "dimension": "INFLATION",
        "frequency": "Q",
        "unit": "index",
        "transformation": {"features": ["level", "quarter_change", "percentile"]},
        "quality_grade": "A",
        "active": True,
    },
    {
        "id": "CENSUS_US_RETAIL_SALES",
        "source_id": "census_us",
        "external_code": "adv44X72",
        "name_zh": "美国零售与餐饮销售额",
        "name_en": "U.S. retail and food services sales, seasonally adjusted",
        "geography": "US",
        "dimension": "REAL",
        "frequency": "M",
        "unit": "millions of dollars",
        "transformation": {"features": ["yoy", "three_month_momentum", "percentile"]},
        "quality_grade": "A",
        "active": True,
    },
    {
        "id": "TREASURY_US_10Y2Y",
        "source_id": "treasury_us",
        "external_code": "DAILY_YIELD_CURVE:BC_10YEAR-BC_2YEAR",
        "name_zh": "美国10年期与2年期国债利差",
        "name_en": "U.S. Treasury 10-year minus 2-year par yield spread",
        "geography": "US",
        "dimension": "CREDIT",
        "frequency": "D",
        "unit": "percentage points",
        "transformation": {"features": ["level", "three_month_change", "percentile"]},
        "quality_grade": "A",
        "active": True,
    },
    {
        "id": "BLS_US_CPI",
        "source_id": "bls",
        "external_code": "CUSR0000SA0",
        "name_zh": "美国居民消费价格指数",
        "name_en": "CPI-U, all items, seasonally adjusted",
        "geography": "US",
        "dimension": "INFLATION",
        "frequency": "M",
        "unit": "index",
        "transformation": {"features": ["yoy", "three_month_momentum", "percentile"]},
        "quality_grade": "A",
        "active": True,
    },
    {
        "id": "BLS_US_UNEMPLOYMENT",
        "source_id": "bls",
        "external_code": "LNS14000000",
        "name_zh": "美国失业率",
        "name_en": "Unemployment rate, seasonally adjusted",
        "geography": "US",
        "dimension": "REAL",
        "frequency": "M",
        "unit": "%",
        "transformation": {"features": ["level", "three_month_change", "percentile"]},
        "quality_grade": "A",
        "active": True,
    },
    {
        "id": "BLS_US_PAYROLLS",
        "source_id": "bls",
        "external_code": "CES0000000001",
        "name_zh": "美国非农就业人数",
        "name_en": "All employees, total nonfarm, seasonally adjusted",
        "geography": "US",
        "dimension": "REAL",
        "frequency": "M",
        "unit": "thousands",
        "transformation": {"features": ["yoy", "three_month_change", "percentile"]},
        "quality_grade": "A",
        "active": True,
    },
    {
        "id": "BOJ_JP_CGPI_YOY",
        "source_id": "boj",
        "external_code": "PR01:PRCG20_2200000000%",
        "name_zh": "日本国内企业商品价格同比",
        "name_en": "Japan Producer Price Index, all commodities, year-on-year",
        "geography": "JP",
        "dimension": "INFLATION",
        "frequency": "M",
        "unit": "%",
        "transformation": {"features": ["level", "three_month_change", "percentile"]},
        "quality_grade": "A",
        "active": True,
    },
    {
        "id": "BOJ_JP_GENERAL_PRICE_OUTLOOK_1Y",
        "source_id": "boj",
        "external_code": "CO:TK99F0000204HCQ00000",
        "name_zh": "日本企业未来一年总体物价预期",
        "name_en": "Tankan all-enterprise general price outlook, one year ahead",
        "geography": "JP",
        "dimension": "INFLATION",
        "frequency": "Q",
        "unit": "%",
        "transformation": {"features": ["level", "quarter_change", "percentile"]},
        "quality_grade": "A",
        "active": True,
    },
    {
        "id": "BOJ_JP_TANKAN_MANUFACTURING",
        "source_id": "boj",
        "external_code": "CO:TK99F1000601GCQ01000",
        "name_zh": "日本短观大型制造业景气判断指数",
        "name_en": "Tankan DI, large manufacturing, actual result",
        "geography": "JP",
        "dimension": "REAL",
        "frequency": "Q",
        "unit": "% points",
        "transformation": {"features": ["level", "quarter_change", "percentile"]},
        "quality_grade": "A",
        "active": True,
    },
    {
        "id": "BOJ_JP_TANKAN_NONMANUFACTURING",
        "source_id": "boj",
        "external_code": "CO:TK99F2000601GCQ01000",
        "name_zh": "日本短观大型非制造业景气判断指数",
        "name_en": "Tankan DI, large nonmanufacturing, actual result",
        "geography": "JP",
        "dimension": "REAL",
        "frequency": "Q",
        "unit": "% points",
        "transformation": {"features": ["level", "quarter_change", "percentile"]},
        "quality_grade": "A",
        "active": True,
    },
    {
        "id": "NBS_CN_GOODS_CPI_YOY",
        "source_id": "nbs_cn",
        "external_code": "OFFICIAL_RELEASE:GOODS_CPI_YOY",
        "name_zh": "中国消费品价格同比",
        "name_en": "China consumer goods CPI, year-on-year",
        "geography": "CN",
        "dimension": "INFLATION",
        "frequency": "M",
        "unit": "%",
        "transformation": {"features": ["level", "three_month_change", "percentile"]},
        "quality_grade": "A",
        "active": True,
    },
    {
        "id": "NBS_CN_SERVICES_CPI_YOY",
        "source_id": "nbs_cn",
        "external_code": "OFFICIAL_RELEASE:SERVICES_CPI_YOY",
        "name_zh": "中国服务价格同比",
        "name_en": "China services CPI, year-on-year",
        "geography": "CN",
        "dimension": "INFLATION",
        "frequency": "M",
        "unit": "%",
        "transformation": {"features": ["level", "three_month_change", "percentile"]},
        "quality_grade": "A",
        "active": True,
    },
    {
        "id": "NBS_CN_CORE_CPI_YOY",
        "source_id": "nbs_cn",
        "external_code": "OFFICIAL_RELEASE:CORE_CPI_YOY",
        "name_zh": "中国核心居民消费价格同比",
        "name_en": "China core CPI excluding food and energy, year-on-year",
        "geography": "CN",
        "dimension": "INFLATION",
        "frequency": "M",
        "unit": "%",
        "transformation": {"features": ["level", "three_month_change", "percentile"]},
        "quality_grade": "A",
        "active": True,
    },
    {
        "id": "NBS_CN_CPI_YOY",
        "source_id": "nbs_cn",
        "external_code": "OFFICIAL_CSV:CPI_YOY",
        "name_zh": "中国居民消费价格同比",
        "name_en": "China CPI, year-on-year",
        "geography": "CN",
        "dimension": "INFLATION",
        "frequency": "M",
        "unit": "%",
        "transformation": {"features": ["level", "three_month_change", "percentile"]},
        "quality_grade": "A",
        "active": True,
    },
    {
        "id": "NBS_CN_PPI_YOY",
        "source_id": "nbs_cn",
        "external_code": "OFFICIAL_CSV:PPI_YOY",
        "name_zh": "中国工业生产者出厂价格同比",
        "name_en": "China PPI, year-on-year",
        "geography": "CN",
        "dimension": "INFLATION",
        "frequency": "M",
        "unit": "%",
        "transformation": {"features": ["level", "three_month_change", "percentile"]},
        "quality_grade": "A",
        "active": True,
    },
    {
        "id": "NBS_CN_INDUSTRIAL_PRODUCTION_YOY",
        "source_id": "nbs_cn",
        "external_code": "OFFICIAL_CSV:INDUSTRIAL_PRODUCTION_YOY",
        "name_zh": "中国规模以上工业增加值同比",
        "name_en": "China industrial production, year-on-year",
        "geography": "CN",
        "dimension": "REAL",
        "frequency": "M",
        "unit": "%",
        "transformation": {"features": ["level", "three_month_change", "percentile"]},
        "quality_grade": "A",
        "active": True,
    },
]


def build_indicator_seed() -> list[dict]:
    rows = []
    for geography, country_code in GEOGRAPHIES.items():
        for template in INDICATOR_TEMPLATES:
            rows.append(
                {
                    "id": f"WB_{geography}_{template['slug']}",
                    "source_id": "world_bank",
                    "external_code": f"{country_code}:{template['external_code']}",
                    "name_zh": template["name_zh"],
                    "name_en": template["name_en"],
                    "geography": geography,
                    "dimension": template["dimension"],
                    "frequency": template["frequency"],
                    "unit": template["unit"],
                    "transformation": template["transformation"],
                    "quality_grade": template["quality_grade"],
                    "active": True,
                }
            )
    return rows + MONTHLY_INDICATORS


def seed_registry(session: Session) -> None:
    for row in SOURCES:
        session.merge(SourceRegistry(**row))
    for row in build_indicator_seed():
        session.merge(IndicatorDefinition(**row))
    session.commit()
